version: "3.8"

services:
  qrcode-alexishayat-me:
    build: .
    container_name: qrcode-alexishayat-me
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true